import pandas as pd
import plotly.graph_objects as go
import streamlit as st
from src.ui.components import header,empty,job_panel,report_actions
from src.services.data import datasets,sales
from src.services.jobs import queue
from src.services.analytics import forecasts
from src.analytics.forecasting import METHODS
from src.services.reports import build_report
from src.core.auth import allowed

def render(ctx):
    header('Demand planning','See what comes next','Compare forecasting methods, inspect held-out accuracy, and plan with uncertainty in view.')
    ds=datasets(ctx)
    if not ds:empty('Sales history needed','Upload a dataset with product identifiers, dates and quantities.');return
    a,b,c,d=st.columns([2,2,1,2])
    with a:dataset=st.selectbox('Dataset',ds,format_func=lambda x:x.name)
    frame=sales(ctx,dataset.id)
    with b:sku=st.selectbox('Product',sorted(frame.sku.unique()))
    with c:horizon=st.selectbox('Days ahead',[7,14,30,90],index=1)
    with d:method=st.selectbox('Method',['Auto benchmark']+METHODS)
    if allowed(ctx,'forecast.run') and st.button('Generate forecast',type='primary'):
        st.session_state.forecast_job=queue(ctx,'forecast',{'dataset_id':dataset.id,'sku':sku,'horizon':horizon,'method':method})
    result=job_panel(ctx,st.session_state.forecast_job) if st.session_state.get('forecast_job') else None
    if result:st.session_state.forecast_result=result
    result=st.session_state.get('forecast_result')
    if not result:
        saved=forecasts(ctx)
        if saved:
            chosen=st.selectbox('Previous forecast',saved,format_func=lambda f:f.sku+' · '+f.model+' · '+str(f.created_at.date()))
            result=chosen.payload
    if not result:
        st.info('Your forecast will appear here when the task completes. Models with downloads need the optional forecasting setup.');return
    hist=pd.DataFrame(result['history']);future=pd.DataFrame(result['forecasts'])
    a,b,c,d=st.columns(4)
    a.metric('Selected method',result['model']);b.metric('Forecast units',f"{future.prediction.sum():,.0f}");c.metric('Holdout MAE',str(result['holdout']['mae']));d.metric('Holdout WAPE',str(result['holdout']['wape_pct'])+'%')
    fig=go.Figure()
    fig.add_trace(go.Scatter(x=hist.date,y=hist.quantity,name='Observed sales',line=dict(color='#0F172A',width=2)))
    fig.add_trace(go.Scatter(x=future.date,y=future.upper,name='Planning band upper',line=dict(width=0),showlegend=False))
    fig.add_trace(go.Scatter(x=future.date,y=future.lower,name='Planning band',fill='tonexty',fillcolor='rgba(15,118,110,.15)',line=dict(width=0)))
    fig.add_trace(go.Scatter(x=future.date,y=future.prediction,name='Forecast',line=dict(color='#0F766E',width=3)))
    fig.update_layout(height=370,margin=dict(l=0,r=0,t=20,b=0),legend=dict(orientation='h'),paper_bgcolor='rgba(0,0,0,0)',plot_bgcolor='rgba(0,0,0,0)',yaxis_title='Units')
    st.plotly_chart(fig,use_container_width=True)
    st.caption('Forecast for '+result.get('sku',sku)+' · history through '+result['train_end'])
    if st.checkbox('Show weekly planning totals'):
        weekly=future.copy();weekly['date']=pd.to_datetime(weekly.date)
        weekly=weekly.set_index('date')[['prediction','lower','upper']].resample('W-SUN').sum().reset_index()
        st.dataframe(weekly,hide_index=True,use_container_width=True)
        st.caption('Daily predictions grouped into calendar weeks; edge weeks may be partial. Summed planning bounds are not calibrated weekly intervals.')
    with st.expander('Evaluation and limitations',expanded=True):
        st.dataframe(result['validation'],hide_index=True,use_container_width=True)
        for note in result['warnings']:st.caption('• '+note)
        if result['failed_models']:st.json(result['failed_models'])
    payload=build_report('Demand forecast '+result.get('sku',sku),'Forecast generated by '+result['model'],{'Forecast':result['forecasts'],'Validation':result['validation']},['Dataset '+result['dataset_id'],'History through '+result['train_end']],result['warnings'],'sales')
    report_actions(ctx,payload,'forecast_report')
