SPECS={
 'orchestrator':{'role':'Orchestrator','goal':'Route the business request safely','task':'Select relevant services and track the case','workflow':'Authorize, classify, assign, review, deliver','tools_state':'Permissions, case ID, stage, bounded retries','output':'Plan and completed case'},
 'research':{'role':'Market researcher','goal':'Find supported product opportunities','task':'Research public product evidence and assortment gaps','workflow':'Search, read, qualify, compare, propose','tools_state':'DuckDuckGo, public-page reader, catalog, dated evidence','output':'Cited opportunity assessment'},
 'analyst':{'role':'Demand analyst','goal':'Produce defensible numerical analysis','task':'Run forecasts and validate results','workflow':'Validate inputs, calculate, backtest, explain','tools_state':'Forecast adapters, dataset version, metrics','output':'Forecast and limitations'},
 'operations':{'role':'Operations specialist','goal':'Maintain suitable stock','task':'Compute replenishment within constraints','workflow':'Reconcile, calculate, constrain, propose','tools_state':'Inventory ledger, EOQ, ROP, safety stock, budget','output':'Purchase proposal awaiting approval'},
 'sales':{'role':'Sales specialist','goal':'Improve selling and retention','task':'Analyze segments, baskets and price scenarios','workflow':'Check data, segment, evaluate, propose','tools_state':'RFM, K-Means, churn, basket analytics','output':'Evidence and campaign proposal'},
 'finance':{'role':'Finance specialist','goal':'Assess margin and affordability','task':'Reconcile sales, costs and expenses','workflow':'Read authorized records, calculate, qualify','tools_state':'Finance permission, actuals, estimates, missing fields','output':'Finance summary'},
 'hr':{'role':'HR assistant','goal':'Support staff planning','task':'Prepare scheduling and policy support','workflow':'Read permitted records, draft, route approval','tools_state':'HR permission, availability, policy evidence','output':'Staffing draft without employment decisions'},
 'knowledge':{'role':'Knowledge researcher','goal':'Retrieve relevant authorized evidence','task':'Search, rank and cite business documents','workflow':'Scope, BM25, FAISS, fuse, rerank','tools_state':'Corpus permissions, chunk IDs, index version','output':'Evidence bundle'},
 'writer':{'role':'Business report writer','goal':'Explain verified findings clearly','task':'Organize results in the requested format','workflow':'Read evidence, write, cite, submit for review','tools_state':'Structured evidence, sources and limitations','output':'Draft answer or report'},
 'reviewer':{'role':'Independent reviewer','goal':'Check evidence and completeness','task':'Review claims, citations, numbers and scope','workflow':'Check, return issues, accept or show evidence fallback','tools_state':'Source allowlist, tool results, bounded agent iterations','output':'Review verdict and final findings'},
}
